camera:
  id: 0
  width: 1280
  height: 720
  fps: 30
  intrinsics_path: "data/camera/cam0.yaml"   # written by eye-cam-calibrate

screen:
  # physical monitor size in meters
  physical_width_m: 0.349
  physical_height_m: 0.241
  # primary screen resolution used by your UI
  res_w: 2880
  res_h: 1800
  # set this if you measured camera→screen distance with a ruler
  camera_to_screen_m: 0.00   # leave absent to auto-probe when RealSense depth is available
  # if the camera principal point is not at the screen center, specify offsets in meters
  camera_offset_x_m: 0.00    # +X is right
  camera_offset_y_m: -0.108    # +Y is down (match your image convention)

  plane_path: data/screen/screen_plane.yaml

backend:
  landmarks: "mediapipe"     # "mediapipe" | "other feature extractors" 

paths:
  sessions_dir: "data/sessions"
  camera_dir: "data/camera"

calibration:
  pattern: "charuco"         # "checkerboard" | "charuco"
  checkerboard:
    cols: 9                  # inner corners across
    rows: 6                  # inner corners down
    square_size_mm: 25.0
    fisheye: false
  charuco:
    squares_x: 5
    squares_y: 7
    square_size_mm: 30.0
    marker_size_mm: 22.0
    aruco_dict: "DICT_5X5_1000"
    detector:
      adaptiveThreshWinSizeMin: 3
      adaptiveThreshWinSizeMax: 23
      adaptiveThreshWinSizeStep: 10
      minMarkerPerimeterRate: 0.03
      maxMarkerPerimeterRate: 4.0
      cornerRefinementMethod: 2    # 0:None 1:Subpix 2:ArucoRefine
samples:
  min_frames: 18
  max_frames: 80
  auto_capture: true
  min_motion_px: 30            # ensure pose diversity
