camera:
  id: 0
  width: 1280
  height: 720
  fps: 30
  intrinsics_path: "data/camera/cam0.yaml"   # written by eye-cam-calibrate

backend:
  landmarks: "mediapipe"     # "mediapipe" | "spiga"

paths:
  sessions_dir: "data/sessions"
  camera_dir: "data/camera"

calibration:
  pattern: "charuco"         # "checkerboard" | "charuco"
  checkerboard:
    cols: 9                  # inner corners across
    rows: 6                  # inner corners down
    square_size_mm: 25.0
    fisheye: false
  charuco:
    squares_x: 5
    squares_y: 7
    square_size_mm: 30.0
    marker_size_mm: 22.0
    aruco_dict: "DICT_5X5_1000"
    detector:
      adaptiveThreshWinSizeMin: 3
      adaptiveThreshWinSizeMax: 23
      adaptiveThreshWinSizeStep: 10
      minMarkerPerimeterRate: 0.03
      maxMarkerPerimeterRate: 4.0
      cornerRefinementMethod: 2    # 0:None 1:Subpix 2:ArucoRefine
samples:
  min_frames: 18
  max_frames: 80
  auto_capture: true
  min_motion_px: 20            # ensure pose diversity
